# Generated by Django 5.0.6 on 2024-11-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('description', models.TextField(blank=True, null=True)),
                ('expense_name', models.CharField(max_length=100)),
                ('dt_account', models.CharField(max_length=100)),
                ('cr_account', models.CharField(max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('number_of_months', models.PositiveIntegerField(default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='expenses_app.entity')),
            ],
        ),
    ]
