# Generated by Django 5.0.6 on 2024-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
