# Generated by Django 5.0.6 on 2024-07-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0003_alter_propertyfundshare_date_of_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage_app.property')),
            ],
        ),
    ]
