# Generated by Django 5.0.6 on 2024-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0004_propertycosthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='rate',
        ),
        migrations.AddField(
            model_name='propertyfundshare',
            name='share_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
