# Generated by Django 5.0.6 on 2024-07-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0005_remove_fund_rate_propertyfundshare_share_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycosthistory',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
