# Generated by Django 5.0.6 on 2024-07-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_app', '0006_alter_propertycosthistory_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertycosthistory',
            options={'verbose_name': 'Property cost history', 'verbose_name_plural': 'Property cost histories'},
        ),
    ]
