# Generated by Django 5.0.6 on 2024-09-12 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='CreditRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_given', to='intercompany_app.company')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_taken', to='intercompany_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='intercompany_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='intercompany_app.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercompany_app.project')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='intercompany_app.company')),
            ],
        ),
    ]
