# Generated by Django 5.0.6 on 2024-09-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='projecttransfer',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projecttransfer',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='creditrelationship',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='creditrelationship',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='projecttransfer',
            name='project',
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_method', models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Daily 360', 'Daily 360')], default='Monthly', max_length=15)),
                ('created', models.DateField()),
                ('finished', models.DateField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='intercompany_app.table')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CreditRelationship',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTransfer',
        ),
    ]
