# Generated by Django 5.0.6 on 2024-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_app', '0002_table_remove_projecttransfer_to_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerow',
            name='gl_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
