# Generated by Django 5.0.6 on 2024-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('investment_date', models.DateField()),
                ('investment_rate', models.FloatField()),
                ('investment_amount', models.IntegerField()),
                ('investment_type', models.CharField(choices=[('Direct Deposit', 'Direct Deposit'), ('Reinvestment', 'Reinvestment')], max_length=15)),
            ],
        ),
    ]
