# Generated by Django 5.0.6 on 2024-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_client_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_amount',
            field=models.FloatField(),
        ),
    ]
