# Generated by Django 5.0.6 on 2024-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0003_alter_client_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='investment_count_method',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], default='Monthly', max_length=15),
        ),
    ]
