# Generated by Django 5.0.6 on 2024-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0004_client_investment_count_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_count_method',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Daily 360', 'Daily 360')], default='Monthly', max_length=15),
        ),
    ]
