# Generated by Django 5.0.6 on 2024-10-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0005_alter_client_investment_count_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_type',
            field=models.CharField(choices=[('Direct Deposit', 'Direct Deposit'), ('Reinvestment', 'Reinvestment'), ('Reinvestment Monthly', 'Reinvestment Monthly')], max_length=50),
        ),
    ]
